### ISSUE TITLE
使用maven报模板解析错误 包括路径和元素等。。

### ISSUE THREAD

**Issue by iver3on** [waylau/spring-security-tutorial#8]
org.xml.sax.SAXParseException: 元素类型 "link" 必须由匹配的结束标记 "</link>" 终止。
at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:203) ~[na:1.8.0_131]
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.fatalError(ErrorHandlerWrapper.java:177) ~[na:1.8.0_131]
	at 

~{fragments/header :: header}

**Comment by iver3on** [comment]
org.thymeleaf.exceptions.TemplateInputException: Error resolving template "~{fragments/header", template might not exist or might not be accessible by any of the configured Template Resolvers (index)

**Comment by waylau** [comment]
你依赖包没有配置对。请使用 Gradle ，或者自行参考 Gradle 的配置，转为 Maven
